


behaviors:
  pioche:
    - excavator1
    - effetmain



properties:
  excavator1:
    type: ExcavatorProperty
    radius: 1
    depth: 1
  effetmain:
    type: HarvestProperty
    effect: SPEED
    amplifier: 2