


behaviors:
  pioche:
    - excavator1
  une_houe_de_max:
    - harvest
    - excava_dirt
    - held_effect

properties:
  excavator1:
    type: excavator
    radius: 1
    depth: 0
    materials:
      - STONE
      - DIRT
  excava_dirt:
    type: excavator
    radius: 1
    depth: 0
    materials:
      - DIRT
      - GRASS_BLOCK