


behaviors:
  pioche:
    - excavator1
  une_houe_de_max:
    - default_harvest
    - excava_dirt
    - click_effect



properties:
  excavator1:
    type: default_excavator
    radius: 1
    depth: 0
    materials:
      - STONE
      - DIRT
  excava_dirt:
    type: default_excavator
    radius: 1
    depth: 0
    materials:
      - DIRT
      - GRASS_BLOCK